INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('2','isaac','robert','femme','femme','2000-4-1','sevran','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('3','raphaël','bonnet','homme','homme','1975-4-9','sevran','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('4','maxime','bonnet','homme','femme','1977-1-15','paris','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('5','victor','bernard','femme','femme','1960-7-10','montpellier','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('6','chloé','petit','femme','femme','1975-4-26','istanbul','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('7','gabriel','blanc','homme','femme','1970-4-15','brest','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('8','adam','girard','homme','homme','1994-8-20','bordeaux','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('9','gabriel','robert','femme','femme','1988-8-11','istanbul','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('10','lina','roche','femme','femme','1987-1-21','paris','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('11','camille','roche','homme','femme','1987-3-5','dubai','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('12','louis','bonnet','femme','homme','1980-8-30','bordeaux','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('13','paul','bernard','femme','homme','1991-4-21','bordeaux','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('14','paul','ricard','homme','femme','1998-2-24','dubai','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('15','quentin','dubois','homme','homme','1976-10-18','bordeaux','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('16','raphaël','dubois','femme','homme','1972-3-28','paris','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('17','camille','bernard','femme','homme','1971-10-12','brest','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('18','chloé','dubois','homme','femme','1971-9-11','paris','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('19','alexandre','ricard','femme','femme','1999-5-27','toulouse','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('20','alexandre','martin','homme','homme','1970-9-24','dubai','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('21','emma','martin','femme','homme','1968-6-13','toulouse','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('22','chloé','roche','femme','homme','1992-2-3','brest','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('23','lina','blanc','homme','homme','1980-6-9','sevran','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('24','chloé','girard','homme','homme','1971-3-21','sevran','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('25','paul','rouge','homme','femme','1968-8-2','brest','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('26','thomas','durex','femme','femme','1971-4-12','dubai','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('27','thomas','dubois','homme','homme','1968-8-24','dubai','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('28','arthur','roche','homme','femme','1972-2-28','paris','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('29','axel','rouge','femme','homme','1996-9-23','toulouse','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('30','camille','robert','homme','homme','1995-5-25','paris','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('31','camille','dubois','femme','homme','1962-6-30','bordeaux','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('32','hugo','ricard','femme','femme','1961-7-21','brest','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('33','jade','bernard','homme','femme','1973-2-15','sevran','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('34','jules','durand','femme','homme','1994-8-4','sevran','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('35','juliette','durex','homme','femme','1968-11-11','toulouse','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('36','lina','thomas','homme','homme','2000-10-30','brest','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('37','louis','dubois','homme','homme','1961-1-2','brest','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('38','enzo','dubois','femme','femme','1981-5-23','sevran','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('39','jules','bernard','homme','femme','1978-9-27','istanbul','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('40','gabriel','martin','femme','femme','1965-5-6','bordeaux','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('41','gabriel','dupont','homme','femme','1986-2-10','toulouse','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('42','raphaël','rouge','femme','femme','1990-6-3','sevran','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('43','léo','dubois','homme','homme','1978-2-26','dubai','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('44','martin','bernard','femme','femme','1969-8-18','istanbul','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('45','nathan','martin','homme','femme','1993-2-28','brest','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('46','noah','durex','femme','femme','1982-3-29','sevran','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('47','thomas','martin','femme','femme','1969-9-26','dubai','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('48','thomas','girard','femme','femme','1976-8-1','dubai','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('49','thomas','dupont','femme','homme','1980-3-6','istanbul','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('50','valentine','roche','homme','homme','1989-8-13','istanbul','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('51','victor','robert','femme','femme','1982-5-22','istanbul','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('52','raphaël','robert','homme','femme','2001-9-4','istanbul','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('53','raphaël','durex','femme','homme','1990-4-20','sevran','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('54','adrien','dubois','femme','homme','1982-1-26','toulouse','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('55','alexandre','dupont','femme','femme','1986-5-10','sevran','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('56','axel','petit','homme','homme','2000-4-11','brest','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('57','camille','dubois','femme','femme','1977-2-30','brest','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('58','louise','bernard','homme','femme','1974-2-24','istanbul','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('59','jules','roche','femme','femme','1998-2-28','bordeaux','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('60','louise','dupont','homme','homme','1963-9-11','brest','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('61','léa','bonnet','homme','femme','1995-2-1','brest','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('62','léa','blanc','femme','homme','1972-4-7','sevran','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('63','gabriel','dupont','femme','femme','1993-7-16','paris','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('64','margaux','durex','femme','homme','1978-7-23','brest','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('65','gabriel','petit','homme','femme','1968-10-9','paris','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('66','martin','bernard','femme','femme','1993-6-29','montpellier','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('67','mathis','petit','femme','femme','1982-4-9','bordeaux','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('68','mohamed','rouge','homme','homme','1992-10-8','sevran','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('69','olivia','girard','femme','femme','1984-10-28','sevran','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('70','sarah','martin','homme','homme','1997-5-2','toulouse','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('71','sarah','roche','homme','femme','1980-9-7','bordeaux','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('72','constance','dupont','homme','homme','1979-5-17','brest','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('73','emna','martin','homme','femme','1962-8-26','dubai','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('74','charlotte','petit','homme','homme','1976-10-30','toulouse','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('75','louis','roche','homme','femme','1992-6-21','montpellier','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('76','ali','girard','femme','femme','1963-3-14','toulouse','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('77','maxime','bernard','femme','femme','2000-3-1','bordeaux','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('78','apolline','roche','femme','homme','1984-3-23','paris','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('79','eden','ricard','homme','femme','2000-10-3','montpellier','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('80','grégoire','bonnet','homme','femme','2001-8-28','paris','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('81','enzo','blanc','homme','femme','1972-10-15','istanbul','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('82','isaac','roche','homme','homme','1961-8-22','istanbul','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('83','juliette','petit','femme','homme','1969-5-7','brest','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('84','benjamin','dupont','femme','femme','1963-2-16','brest','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('85','lina','durex','femme','femme','1997-3-12','istanbul','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('86','charles','durand','femme','homme','1982-6-9','bordeaux','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('87','inaya','dubois','homme','femme','1991-10-12','montpellier','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('88','margaux','ricard','homme','femme','1987-1-5','istanbul','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('89','luna','rouge','femme','homme','1962-8-9','dubai','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('90','noah','dupont','homme','homme','1993-4-29','dubai','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('91','nathanaël','petit','femme','femme','1997-11-14','montpellier','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('92','alice','robert','homme','homme','1962-8-16','paris','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('93','alice','girard','femme','homme','1983-1-27','montpellier','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('94','clara','ricard','homme','femme','1969-2-14','toulouse','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('95','clément','durand','homme','femme','1966-5-12','dubai','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('96','mathis','dupont','homme','femme','1984-4-19','paris','Je suis le plus beau des rebeus');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('97','maxime','rouge','homme','homme','1989-5-16','toulouse','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('98','ethan','dupont','homme','homme','1983-2-17','paris','Alper is the best');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('99','mohamed','durex','femme','homme','1978-3-21','istanbul','I LOVE TWIX');
INSERT INTO profile_indiv (id_usr,prenom,nom,sexe,orientation_sexe,date_naissance,ville,description) VALUES ('100','lucas','girard','homme','femme','1982-5-21','istanbul','Alper is the best');
